---
name: HTML Lints

on:
  push:
    branches:
      - '**'
      
jobs:
    HTML_Lint:
        runs-on: ubuntu-latest
        container:
          image: ghcr.io/cradle8810/htmllint:latest
        steps:

        - name: Checkout
          uses: actions/checkout@v3

        - name: HTMLlint Initialize
          run: htmllint init

        - name: Execute HTMLlint
          run: htmllint
