---
name: Make sitemap.txt

on:
  push:
    branches:
      - 'master'

jobs:
    Sitemap_txt:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: find html files and output as sitemap.txt
          run: | 
            find . -type f -name "*.html" | \
            sed 's#\.\/#http:\/\/hayaworld\.net/#g' | \
            sed 's#\/www##g' \
            > www/sitemap.txt

        - name: Upload sitemap.txt as artifacts
          uses: actions/upload-artifact@v4
          with:
            name: www/sitemap.txt
            path: sitemap.txt
