---
name: HTML Lints

on:
  push:
    branches:
      - '**'
      
jobs:
    HTML_Lint:
        runs-on: ubuntu-latest
        container:
          image: ghcr.io/cradle8810/htmllint:latest
        steps:

        - name: Checkout
          uses: actions/checkout@v3

        - name: Execute HTMLlint
          run: htmllint

    Sitemap_txt:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: find html files and output as sitemap.txt
          run: | 
            find . -type f -name "*.html" | \
            sed 's#\.\/#http:\/\/hayaworld\.net/#g' | \
            sed 's#\/www##g' \
            > www/sitemap.txt

        - name: View sitemap.txt
          run: cat "www/sitemap.txt"

        - name: Upload sitemap.txt as artifacts
          uses: actions/upload-artifact@v4
          with:
            name: sitemap.txt
            path: www/sitemap.txt

    Deployment:
        needs:
            - HTML_Lint
            - Sitemap_txt
        if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/auto_deploy')
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
